title: Mohamed Elbeltagi # your name (or website title) here
title_font_size: 24px
logo: "/resources/myphoto.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)  
  Data Science|Machine Learning|Physics
  <br><br>
  <a href="https://linkedin.com/in/mohamed-elbeltagi-016995107">LinkedIn</a> |
  <a href="/resources/Mohamed_Elbeltagi_Resume.pdf">My Resume</a> | 
  <a href="https://scholar.google.com/citations?user=Wv_oG8QAAAAJ&hl=en">My Publications</a>
  <br><br>
  Languages: Python, SQL, JavaScript, C++, Java
  <br><br>
  Libraries/Tools: Pandas, scikit-learn, Matplotlib, PyTorch, Hugging Face Transformers, Apache Airflow, Jupyter Notebooks, Flask, AWS, GCP, Git, Selenium, Docker

 


theme: jekyll-theme-minimal
